[package]
name = "jetstreamer-plugin"
description = "Support crate for Jetstreamer containing plugin framework abstractions and utilities"
keywords.workspace = true
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
default = ["clickhouse"]
clickhouse = ["dep:clickhouse"]

[dependencies]
jetstreamer-firehose.workspace = true

base64.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
solana-message.workspace = true
solana-address.workspace = true
tokio.workspace = true
log.workspace = true
clickhouse = { workspace = true, optional = true }
futures-util.workspace = true
thiserror.workspace = true
sha2.workspace = true
dashmap.workspace = true
once_cell.workspace = true
solana-sdk-ids.workspace = true
solana-entry.workspace = true
solana-hash.workspace = true
solana-ledger.workspace = true
solana-transaction.workspace = true
url.workspace = true
solana-keypair = "3"
